# Generated by Django 2.2.10 on 2021-05-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myshow.Category'),
        ),
    ]
